### ISSUE TITLE
老板.更新下呗?

### ISSUE THREAD

**Issue by hemiaoio** [yuzukwok/Abp.Web.Api.SwaggerTool#3]
目前用的1.1.3版本的ABP.不使用SwaggerTool . swagger 能正常显示,使用SwaggerTool后,出现**转换错误**.错误如下:
  `500 : {
    "message": "An error has occurred.",
    "exceptionMessage": "One or more errors occurred.",
    "exceptionType": "System.AggregateException",
    "stackTrace": "at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
                    at System.Threading.Tasks.Task`1.get_Result()
                    at Abp.WebApi.Controllers.ResultWrapperHandler.<>c__DisplayClass2_0.<SendAsync>b__0(Task`1 task) in D:\\Halil\\Github\\aspnetboilerplate\\src\\Abp.Web.Api\\WebApi\\Controllers\\ResultWrapperHandler.cs:line 32
                    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                    at System.Threading.Tasks.Task.Execute()
                    --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()",
    "innerException": {
        "message": "An error has occurred.",
        "exceptionMessage": "Specified cast is not valid.",
        "exceptionType": "System.InvalidCastException",
        "stackTrace": " at Abp.Web.Api.SwaggerTool.ApplyDocumentVendorExtensions.Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer) in ApplyDocumentVendorExtensions.cs:line 65
                        at Swashbuckle.Swagger.SwaggerGenerator.GetSwagger(String rootUrl, String apiVersion)
                        at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                        at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                        at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                        at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                        at System.Web.Http.Cors.CorsMessageHandler.<SendAsync>d__0.MoveNext()"
    }} http://localhost:6240/swagger/docs/v1`

**Comment by hemiaoio** [comment]
因为土牛不按照套路出牌...  NotificationSeverity 这个枚举使用的是byte类型...在ApplyDocumentVendorExtensions 里面做枚举转换的时候出现上述错误.
@Row 67 & 71 (int)enumOption --> Convert.ToInt32(enumOption )
解决
